name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        name: [gcc8, gcc9, gcc10, gcc11]
        include:
          - name: gcc8
            toolchain: ""
          - name: gcc9
            toolchain: ""
          - name: gcc10
            toolchain: ""
          - name: gcc11
            toolchain: ""

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Bulid docker image
      working-directory: ${{runner.workspace}}/pisa/test/docker/${{matrix.name}}
      shell: bash
      run: |
          docker build . -t test-image
          docker run --name test -v ${{runner.workspace}}/pisa:/pisa -d --rm -it test-image

    - name: Create Build Environment
      shell: bash
      run: docker exec test cmake -E make_directory /pisa/build

    - name: Configure
      shell: bash
      run: docker exec -w /pisa/build test cmake /pisa/build -DCMAKE_BUILD_TYPE=Debug -DPISA_BUILD_TOOLS=ON -DPISA_CI_BUILD=ON ${{matrix.toolchain}} ..

    - name: Build
      shell: bash
      run: docker exec -w /pisa/build test cmake --build . --config Debug -- -j 4

    - name: Test
      shell: bash
      run: docker exec -w /pisa/build test ctest -VV -j 4
